[package]
name = "ethash"
version = "1.11.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]

[dependencies]
crunchy = "0.1.0"
either = "1.0.0"
ethereum-types = "0.3"
keccak-hash = { path = "../util/hash" }
log = "0.3"
memmap = "0.6"
parking_lot = "0.5"
primal = "0.2.3"

[dev-dependencies]
tempdir = "0.3"

[features]
benches = []
